spring.application.name=ChargerProject

 # DataSource Setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.125.121.186:3306/chargerdb
# spring.datasource.username=roo
spring.datasource.username=401
spring.datasource.password=tiger
 # JPA Setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
 
kakao.api.key=a4d144598ece27bb47f2314ec5400e40
#oh
#dd.api.key=ljMrVJAnNyhtH3TuHxkAPcbx40ZjpfKZsu9dzYfpLBzj09wt3S%2F%2FjzAOa%2Bab8wBVFT0mGOkmjbH2jTaeV3PZiw%3D%3D
#uyee
dd.api.key=zgGPnDlcjrWs%2FabF%2FDt%2F%2B%2BWrhBFG%2FVe2S8cfn18zfFtlJhTp8ZDb%2FYAqELJFsqflyZVMMwofrLr5qlhbNo5%2F%2BA%3D%3D
#Ryu
#WDAOSPm8%2FnUfrHlYki3BTmYVFPFAd0yJgPZvnN91UplaeIE%2FVQRiP3%2Fxxyx5BNJxhLIpKtLn73z%2BdvBRgjJtRA%3D%3D
#dd.api.key=SqqAk1q%2BvWV6MAwbCqRTzoFfuIUi8A8sMtPEeDWsU%2Fs8OGT8DcGP4VGzGkYHmJoAzS60SjWRMeMRGFwq12ScGQ%3D%3D
dd.api.key.decode=SqqAk1q+vWV6MAwbCqRTzoFfuIUi8A8sMtPEeDWsU/s8OGT8DcGP4VGzGkYHmJoAzS60SjWRMeMRGFwq12ScGQ==